window_padding_width 10
# background #1E1E1E
# foreground #D4D4D4
# Font Configuration
font_family MesloLGS Nerd Font Mono
font_size         14.0

# Shape definition
cursor_shape      block

# Layout and Shell Integration
modify_font line_height -2
shell_integration no-cursor

background_opacity 0.96
# background #1E1E1E
# foreground #D4D4D4


# BEGIN_KITTY_THEME
# Gruvbox Material Dark Soft
include current-theme.conf
# END_KITTY_THEME
